# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20171031_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='daily_reports_allowed',
            new_name='day_reports_allowed',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='weekly_reports_allowed',
            new_name='week_reports_allowed',
        ),
        migrations.AddField(
            model_name='profile',
            name='month_reports_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
