# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-10 11:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20171108_0721'),
        ('api', '0028_check_nag_time'),
    ]

    operations = [
    ]
